### ISSUE TITLE
Deploy to CloudFront distribution based on stages

### ISSUE THREAD

**Issue by AllegraChen** [serverless-operations/serverless-lambda-edge-pre-existing-cloudfront#14]
I hope to deploy to different existing CloudFront distributions based on different stages. However, this plugin does not seem to provide me with that extra layer of functionality. The `validStages` property that we can configure at the `custom` section does not do the work since we are not able to set the `validStages` property for each `preExistingCloudFront` object.
````yaml
custom:
  lambdaEdgePreExistingCloudFront: # this configuration applies to every preExistingCloudFront distribution
    validStages:
      - staging
      - production
```` 
Therefore, I was thinking that I could open a pull request to add that extra feature. I hope that we could have a `stage` property for each `preExistingCloudFront` object under the `event` array like this:
````yaml
functions:
  viewerRequest:
    handler: lambdaEdge/viewerRequest.handler
    events:
      - preExistingCloudFront:
          distributionId: xxxxxxx
          eventType: viewer-request
          pathPattern: '*' 
          includeBody: false
          stage: dev # specify the stage when the lambda function is deployed to this cloudfront distribution
````

See detailed implementation in PR #15

**Comment by jonasbarsten** [comment]
We use the "serverless-plugin-ifelse" to define if the lambda@edge should be deployed or not and yaml logic to define the distribution IDs:

```
custom:
  cloudFrontDistIds:
      dev: xxx
      prod: yyy
  cloudFrontDistId: ${self:custom.cloudFrontDistIds.${self:custom.stage}, self:custom.cloudFrontDistIds.dev}
  ...
  serverlessIfElse:
    - If: '"${self:custom.stage}" != "${self:custom.resourcesStage}"'
      Exclude:
        - functions.lambdaEdgeTest
```
