### ISSUE TITLE
Lambda does not deploy to edge

### ISSUE THREAD

**Issue by jwerre** [serverless-operations/serverless-lambda-edge-pre-existing-cloudfront#5]
Not sure whats happening but when I deploy CloudFront trigger is not attached. It appears the [`after:aws:deploy:finalize:cleanup`](https://github.com/serverless-operations/serverless-lambda-edge-pre-existing-cloudfront/blob/master/index.js#L13) hook is not triggering. Here's my yaml if that helps:

```yaml
---
service: my-lambda-edge

provider:
  name: aws
  region: us-east-1
  stage: ${opt:stage, 'staging'}
  runtime: nodejs12.x
  timeout: 120
  stackName: ${self:service}-${self:provider.stage}
  logRetentionInDays: 90
  deploymentBucket:
    name: my-lambda-edge-bucket
  role: my-iam-role
  environment:
    NODE_ENV: ${self:provider.stage}

custom:
  distributions:
    staging: -------------
    production: -------------
  lambdaEdgePreExistingCloudFront:
    validStages:
      - staging
      - production

package:
  exclude:
    - ./**
  include:
    - functions/*.js

functions:

  request:
    handler: functions/request.handler
    events:
      - preExistingCloudFront:
          distributionId: ${self:custom.distributions.${opt:stage, self:provider.stage}}
          eventType: origin-request
          pathPattern: '*'
          includeBody: false


  response:
    handler: functions/response.handler
    events:
      - preExistingCloudFront:
          distributionId: ${self:custom.distributions.${opt:stage, self:provider.stage}}
          eventType: origin-response
          pathPattern: '*'
          includeBody: false


plugins:
  - serverless-lambda-edge-pre-existing-cloudfront
```

```bash
sls --version
Framework Core: 1.76.1
Plugin: 3.6.17
SDK: 2.3.1
Components: 2.32.0
```
